### ISSUE TITLE
How could I build dependency into try-puppeteer docker

### ISSUE THREAD

**Issue by xiaomingdaily** [ebidel/try-puppeteer#24]
Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at [eval]:2:11
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:643:30)
    at evalScript (bootstrap_node.js:462:27)

**Comment by ebidel** [comment]
You can't import your own libraries using this tool.
